<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <AssemblyName>ActivityPub.Misskey.Blazor.Client</AssemblyName>
    <RootNamespace>ActivityPub.Misskey.Blazor.Client</RootNamespace>
    <StaticWebAssetBasePath>app</StaticWebAssetBasePath>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../ActivityPub.Misskey.Blazor/ActivityPub.Misskey.Blazor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ServiceWorker Include="wwwroot/service-worker.js"
                   PublishedContent="wwwroot/service-worker.published.js" />
  </ItemGroup>
</Project>
