<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../ActivityPub.Application/ActivityPub.Application.csproj" />
    <ProjectReference Include="../ActivityPub.Domain/ActivityPub.Domain.csproj" />
  </ItemGroup>
</Project>
