using System.Text.RegularExpressions;

namespace ActivityPub.Misskey.Blazor.Presentation;

/// <summary>
/// Counts display characters with the exact <c>stringz@2.1.0</c>/<c>char-regex@1.0.2</c>
/// contract used by Misskey 12.119.2.
/// </summary>
internal static partial class MisskeyStringLength
{
    public static int Count(string value)
    {
        ArgumentNullException.ThrowIfNull(value);
        return StringzCharacter().Count(value);
    }

    // This is the regex generated by char-regex@1.0.2, which is MIT licensed. Keeping the
    // pinned expression is intentional: current Unicode grapheme segmentation differs from
    // the historical character counter visible in Misskey 12.119.2.
    [GeneratedRegex(
        "(?:\\ud83c\\udff4\\udb40\\udc67\\udb40\\udc62\\udb40(?:\\udc65|\\udc73|\\udc77)\\udb40(?:\\udc6e|\\udc63|\\udc6c)\\udb40(?:\\udc67|\\udc74|\\udc73)\\udb40\\udc7f)|\\ud83c[\\udffb-\\udfff](?=\\ud83c[\\udffb-\\udfff])|(?:[^\\ud800-\\udfff][\\u0300-\\u036f\\ufe20-\\ufe2f\\u20d0-\\u20ff\\u1ab0-\\u1aff\\u1dc0-\\u1dff]?|[\\u0300-\\u036f\\ufe20-\\ufe2f\\u20d0-\\u20ff\\u1ab0-\\u1aff\\u1dc0-\\u1dff]|(?:\\uD83C[\\uDDE6-\\uDDFF]){2}|[\\ud800-\\udbff][\\udc00-\\udfff]|[\\ud800-\\udfff]|[\\uD83D\\uDC69\\uD83C\\uDFFB\\u200D\\uD83C\\uDF93])[\\ufe0e\\ufe0f]?(?:[\\u0300-\\u036f\\ufe20-\\ufe2f\\u20d0-\\u20ff\\u1ab0-\\u1aff\\u1dc0-\\u1dff]|\\ud83c[\\udffb-\\udfff])?(?:\\u200d(?:[^\\ud800-\\udfff]|(?:\\uD83C[\\uDDE6-\\uDDFF]){2}|[\\ud800-\\udbff][\\udc00-\\udfff])[\\ufe0e\\ufe0f]?(?:[\\u0300-\\u036f\\ufe20-\\ufe2f\\u20d0-\\u20ff\\u1ab0-\\u1aff\\u1dc0-\\u1dff]|\\ud83c[\\udffb-\\udfff])?)*",
        RegexOptions.CultureInvariant)]
    private static partial Regex StringzCharacter();
}
